version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=datn_website_fshoes
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - ./sql/datn_website_fshoes.sql:/docker-entrypoint-initdb.d/datn_website_fshoes.sql

  # Container cho ứng dụng Spring Boot
  springboot-app:
    build:
      context: ./back_end/.
      dockerfile: Dockerfile
    container_name: springboot-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/datn_website_fshoes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    volumes:
      - ./logs:/app/logs

  # Container cho ứng dụng ReactJS
  react-app:
    build:
      context: ./font_end/.
      dockerfile: Dockerfile
    container_name: react-container
    ports:
      - "3000:80"
