version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=datn_website_fshoes
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - ./sql/datn_website_fshoes.sql:/docker-entrypoint-initdb.d/datn_website_fshoes.sql

  frontend:
    build: ./font_end
    ports:
      - "3000:3000"

  backend:
    build: ./back_end
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/datn_website_fshoes?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db
